name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: auth
          MYSQL_ROOT_PASSWORD: 0000
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 3306 && echo "MySQL is up!" && break
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Build with Gradle
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: ./gradlew build
